### ISSUE TITLE
tkt-maintenance-public-display

### ISSUE THREAD

**Issue by joyously** [TukuToi/tukutoi-maintenance#18]
For the `<html>` tag, themes usually use
`<html <?php language_attributes(); ?>>`
and then
`<meta charset="<?php bloginfo( 'charset' ); ?>">`
along with a meta tag for the viewport width so it looks right on mobile.

I see you call `wp_head()`, I guess to get your style and script output, and I saw where you make the plugin's script and style overwrite everything else. But core also outputs the `<title>` tag there, although you have one in this file.

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/partials/tkt-maintenance-public-display.php#L49
https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/partials/tkt-maintenance-public-display.php#L63

Do the class names take into account RTL languages? Do the styles?

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/partials/tkt-maintenance-public-display.php#L59

Why the inline style, when you load a stylesheet? Inline is harder for novices to override.

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/public/partials/tkt-maintenance-public-display.php#L79-L80

So the JS option is supposed to include the `<script>` tag?

**Comment by smileBeda** [comment]
Good points in here, I will have to revisit this and enhance it

**Comment by smileBeda** [comment]
Removed title tag
WP Does not allow storing JS nor CSS that way, thus, this became 100% obsolete.
Also removed inline style for the timer and added to CSS file
Added language attributes and viewport tag.

---

Bottom left is regardless language. The user can add his own PHP template if they want a bottom right footer.
