### ISSUE TITLE
readme file 

### ISSUE THREAD

**Issue by joyously** [TukuToi/tukutoi-maintenance#8]
https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/README.txt#L15
should be "Coming Soon"

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/README.txt#L27
There is no "native WordPress Settings > Maintenance Menu"

https://github.com/TukuToi/tkt-maintenance/blob/18c552f0089296be71e39d1c9521a61df0f6d6e1/README.txt#L31
Shouldn't this be unlimited? CSS max-width:100% makes any image resize to its container...

**Comment by smileBeda** [comment]
Thanks!

Issues are fixed and Image Description update to better reflect requirements, suggestions.
